### ISSUE TITLE
pygame.event.wait()

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/RunestoneExtensions#14]
Treba implementirati i ovu metodu. Ako u event queue ima nešto vraća jedan event, a ako nema ništa onda čeka.

Ako nemamo bolju ideju, može da se čeka u petlji, pa da se stavi sleep od npr. 10ms  u tu petlju.

**Comment by denkoRa** [comment]
Malo je ovo problematicno, u javascriptu nema sleep, tako da ne znam kako da uspavam a da oslobodim CPU na neko vreme.
