### ISSUE TITLE
pygame.image

### ISSUE THREAD

**Issue by filipmaric** [Petlja/RunestoneExtensions#16]
Omogućiti učitavanje i prikaz slika. Dovoljno je za početak da na sistemu postoji samo par sličica koje se mogu učitati (npr. samo cat.png i mouse.png). Vidi primer "Учитавање и приказ слика" u pygame-prirucnik/_sources/Crtanje.rst.

**Comment by denkoRa** [comment]
Proradilo je ovo, moze da se vidi na azuriranom [draftu](https://petljaprod-staging-3.azurewebsites.net/BubbleBee/r/lekcije/pygame-prirucnik/crtanje#)

**Comment by filipmaric** [comment]
Odlično! Hvala! Ostaje još samo pitanje prebacivanja sličica u build/pygame-prirucnik/_images. Pretpostavljam da to mora ručno da se uradi za sve slike koje ćemo koristiti?
Filip

**Comment by denkoRa** [comment]
Da treba slicice rucno  ubactiti u _images u root diru.

**Comment by vasiljevic** [comment]
Da razjasnim, sličica koja je u `_images` u root-u priručnika se kopira u `build/pygame-prirucnik/_images` samo ukoliko se referiše iz rst fajlova (`image` direktiva).

Sa druge strane, svakako treba imati u priručniku negde izlistano
koje su sve sličice na raspolaganju (poglavlje na kraju kao prilog, npr.), a kad se to uradi, onda će se sličice i kopirati :) 

pitanje je jedino da li treba napraviti neki podfolder od `_images` kao osnovni folder iz koga pygame učitava slike

**Comment by filipmaric** [comment]
Lepo :) Ne bih uvodio poddirektorijum, jer ce onda i u lokalu morati da ga prave, javlja se pitanje putanje i slicno. Najcistije je samo ime slike i to je to.
