### ISSUE TITLE
Parametar `onlymain` u opciji `:passivecode:`

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/RunestoneExtensions#21]
Ako se navede npr:
```
.. activecode:: id99
    :passivecode: onlymain
    :includesrc: src/p99.py
```
To znači da se će se iz source-a prikaže samo `main` sekcija. Ovo je upravo namenjeno za slučaj da se source čita iz fajla (kao u primeru, mada nema razloga da ne radi i kada se neposredno navede kod), jer onda u priručniku može da se prikaže samo ključni deo koda, a da u fajlu postoji kompletan source koji se može testirati.

Napomena: ako se u kombinaciji sa `:passivecode: onlymain` koristi i `:autorun:`, tada se izvršava ceo program, a ne samo to što je prikazano iz `main` sekcije.

**Comment by denkoRa** [comment]
Jedna stvar mora samo da bude jasna kod opcija.
Opcija moze da bude flag true/false ili da ima neku vrednost. 
Do sada je passivecode bila flag, a sa ovom promenom ce dobiti svoju vrednost, dakle svuda gde je stajalo `:passivecode:` kao flag u rst-u, mora da se doda neka vrednost na to.

**Comment by vasiljevic** [comment]
A ako se ne doda vrednost, da li to znači da je vrednost prazan string (ili tako nešto) ili tada ondam puca sintaksna greška u RST-u što nema vreednost?

**Comment by denkoRa** [comment]
Vrednost je prazan string, ali prazan string nam govori i da opcija nije ukljucena, tako da tu imamo dvosmislenost. Ja predlazem da stoji 

1. `:passivecode: true` kada hocemo samo passivecode editor
2. `:passivecode: onlymain` kada hocemo samo main sekciju

**Comment by vasiljevic** [comment]
Dogovoreno. Trebalo bi onda i da prođeš kod u pygame priručniku i da uradiš dodavanje `true` gde treba
