### ISSUE TITLE
Podrska za dogadjaje tastature

### ISSUE THREAD

**Issue by filipmaric** [Petlja/RunestoneExtensions#26]
- Dodati podrsku za pg.KEYUP

Ovim bi i prvi primer u Dogadjaji.rst trebalo da proradi

**Comment by milenkoviclazar** [comment]
Podrška je dodata u pygame4skulpt u _keyup_ branch. Proverio sam i prvi primer u Dogadjaji.rst sada radi.

**Comment by vasiljevic** [comment]
mergeovao sam i kopirao u RunestoneExtensions
