### ISSUE TITLE
Iskljuciti strelice osim ako ih autor ne ukljuci

### ISSUE THREAD

**Issue by filipmaric** [Petlja/RunestoneExtensions#29]
Strelice koje odmenjuju dogadjaje tastature se uvek prikazuju i cini mi se da opterecuju one najjednostavnije primere (dao sam malo Ani da gleda danas neke crteze i odmah se zakacila za te strelice i pitala se cemu sluze, a zapravo sve do dela o dogadjajima nemaju nikakvu svrhu). Bolje bi bilo da ih autor moze ukljuciti (ili bar iskljuciti) po potrebi.
Filip

**Comment by vasiljevic** [comment]
Hajde za početak da zakomentarišemo ili stavimo "display: none" na strelice, a da posle objavljivanja beta verzije sredimo opciono uključivanje strelica kada se očekuju odgovarajući eventi.
