### ISSUE TITLE
arc i ellipse bug

### ISSUE THREAD

**Issue by filipmaric** [Petlja/RunestoneExtensions#31]
Crtanje elipse ne radi. Pretpostavljam da je uzrok to sto ne radi ni arc od `0` do `2*math.pi` - u PyGame to crta krug, a u pregledacu nista (radi ako se od `2*math.pi` oduzme 0.0001).

**Comment by filipmaric** [comment]
Mislim da je ovaj deo koda sporan:

~~~
        if (Math.abs(angles[1] - 2 * Math.PI) < 1e-5) {
            angles[1] = 0;
        }
~~~

**Comment by vasiljevic** [comment]
Treba proveriti da se dobija isto ponašanje kao Pygame i  kada je ugao veći od 2*PI (za epsilon i za više).

**Comment by denkoRa** [comment]
Provericu ovo, znam da je malo skakljiva prica oko uglova jer se racunaju u suprotnim smerovima u js u odnosu na pygame. 
Nisam siguran sto sam postavio ovaj uslov, moguce da je zbog nekog corner case-a.

**Comment by denkoRa** [comment]
Mislim da radi dobro bez tog dela koda, testirao sam na nekim basic primerima.
