### ISSUE TITLE
PNG providnost ne radi kako treba

### ISSUE THREAD

**Issue by filipmaric** [Petlja/RunestoneExtensions#32]
Za razliku od PyGame u lokalu, na vebu ne radi PNG providnost. Pogledati primer setanje_lika_tastaturom u Dogadjaji.rst.

**Comment by vasiljevic** [comment]
Kanvas može da ima providnu pozadinu, tj. ima alfa kanal, samo je u nekom koraku zakucana pozadina ili izgubljen alfa kanal.
