### ISSUE TITLE
Pygame u modalnom prozoru

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/RunestoneExtensions#6]
Pygame treba da otvara modalni prozor tipa:
https://www.w3schools.com/howto/howto_css_modals.asp

Klikovi koji zatvaraju modalni prozor zapravo bi generisali QUIT event u Pygame, a pygame.quit() bi zatvaralo modalni prozor.

Time postižemo 2 stvari:
- Pygame prozor se ne gura pored (ili ispod) izvornog koda na istoj strani, što može da je zgodno za kratke primere kornjača grafike, ali nije baš za Pygame. 
- Pygame primeri su interaktivni i doživljaj te interakcije će sa modalnim prozorom biti prirodniji
- Pygame primeri su uglavnom takvi da se vrte dok se ne desi QUIT događaj zbog čega je ptorebno da korisnik mora izađe iz izvršavanja Pygame programa da bi išao dalje. 

Ideja implementacije je da se isti div u okviru koga se pravi canvas postane modalna pozadina, a otvaranje i zatvaranje modalnog prozora se svodi na postavljanje CSS klase (a možda i neposredno stila) u taj div.

Prateća CSS pravila bi išla template u RunstoneExtension kao CSS koji se registruje u setupu pygamelib ekstenzije:
https://github.com/Petlja/RunestoneExtensions/blob/95153494fd4aaa6456cfd715375ce123e139e632/runestone_petlja_ext/pygamelib/pygamelib.py#L1

Sve ostalo bi se uradilo u okviru pygame4skulpt, u delu koda:
https://github.com/Petlja/pygame4skulpt/blob/ad91c1af8b2e4f927e760a9198759ec2f9f61a27/pygamelib/pygamelib.js#L122

Tu bi se dinamični napravilo sve što treba od html-a.

Kasnije bi na modalnom prozoru mogli da se dodaju i dugmići za strelice koji generišu odgovarajuće keyboard evente, tako da može da se koristi na mobilnom (ovo može biti i u zavisnosti od toga da li je detektovan mobilni browser).

**Comment by filipmaric** [comment]
Bilo koja sintaksička greška u programu ostavlja modal otvoren i potpuno zablokiran. Deluje mi da samo refresh cele strane može da ga isključi.

**Comment by filipmaric** [comment]
Dogadjaji tastature se propagiraju ispod modala i uzrokuju skrolovanje prozora. Uraditi preventDefault.
