### ISSUE TITLE
Srpska lokalizacija u publikovanoj verziji

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/RunestoneExtensions#8]
U publikovanoj verziji nije podešeno srpski jezik, pa ne radi lokalizacija za srpski.

 Naime u „html“ tagu treba da imamo atribut „lang="sr-Cyrl"“. Može se pogledati bilo koji generisan HTML sto ga pravi runestone build. Generalno bi trebalo isti taj jezik koji je konfigurisan u setup.py da na kraju završi i u HTML-u koji se publikuje.

**Comment by denkoRa** [comment]
Ovde se javlja problem da mi ugradjujemo content koji je generisan runestone-om u nasu html stranu, ne kopira se ceo html koji je izgenerisan.

**Comment by vasiljevic** [comment]
Probaj tako. Svakako postoji mogućnost da se iz javascripta postavi aktuelan jezik, pretpostavljam da je to to što si našao.

Samo jedan detalj, "lang" se treba postaviti u vreme generisanja, gde se dohvati konfigurisana vrendost za language. Najverovatnije će trebati da se ubaci nešto negde u template da se generiše direktno odgovarajuća ninija javascripta u "script" tagu.

**Comment by denkoRa** [comment]
To je dobro pitanje u koji template ubaciti.
Bilo bi dobro ako postoji nacin da se setuje javascript varijabla iz python-a.
Svakako najlaksi nacin je da na serveru ubacimo ovo parce koda u javascript i manuelno izaberemo srpski, ali to verovatno ne zelimo.

**Comment by vasiljevic** [comment]
Jedini put kojim nešto iz Pythona stigne u Javascript jeste preko onoga što python izgeneriše, jer je vreme izvršavanja razdvojeno.

Razmisli da dodaš negde u kodu koji se koristi kod publikovanja, to ima rezona jer tu problem i nastaje, a tu svašta nešto sređuješ i dodaješ.

**Comment by denkoRa** [comment]
Prilikom publikovanja nista ne zavrsava na serveru sto se tice skriptova.
Taj proces komunicira iskljuivo sa bazom, tako da mislim da tu ne moze da se fixuje.

**Comment by vasiljevic** [comment]
iz perspektive publikovanja imamo finski javaskript koji setuje na srpski, valjda može negde da se udene

**Comment by denkoRa** [comment]
pa mozemo mi da imamo skript na serveru koji setuje na srpski, ali da li je to ok resenje?

**Comment by vasiljevic** [comment]
OK je. 

Zapravo, ako se taj skript učitava samo za strane gde je priručnik na srpskom onda je skroz OK, a ako se učitava za sve web strane onda je za sada OK (može posle da se desi da na nakom drugom delu sajta treba lokalizacija za latikicu).
